# Generated by Django 4.0.3 on 2022-03-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='examMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='some string', max_length=100)),
                ('question', models.FileField(default='', upload_to='')),
                ('script', models.FileField(default='', upload_to='')),
            ],
        ),
    ]
